### ISSUE TITLE
"Dispenser updated" message location

### ISSUE THREAD

**Issue by jellewie** [jellewie/Arduino-CocktailMachine#7]
"Dispenser updated" message is over the first item in the list. Which doesn't look nice, and editing the first one is more annoying than needed. There is room enough on the screen to put it a bit up or something

![image](https://user-images.githubusercontent.com/1545223/188269209-06531668-e31b-4e35-adfd-493040462e39.png)

**Comment by jespertheend** [comment]
Toasts cannot appear outside the dialog window, so I could either:
1. Move it up until it touches the edge of the dialog, but this doesn't look as nice:
![image](https://user-images.githubusercontent.com/2737650/189552915-eb36d19d-cab3-485a-b8f4-b321dc26df30.png)

2. Add some padding to the top of the dialog But this means there will permanently be empty space above all dialogs:
![image](https://user-images.githubusercontent.com/2737650/189552960-dfc5f0b4-e550-43de-81a0-c2414ba81221.png)

3. Rewrite how dialogs work, which would allow placing toasts outside of them, but this takes a significant amount of time that I don't think will be worth it.
4. Alternatively we could wait for pop-ups to be available, which I think might allow us to place toasts outside of dialogs as well. It seems like they plan on shipping this [in Chrome 110](https://chromestatus.com/feature/5463833265045504).

Personally I prefer option 2 the most, as it's guaranteed to not cover anything and option 1 looks a little wonky imo. The drink customization dialog doesn't have toasts so that can stay as is, but the other dialogs already have a bunch of empty space at the bottom, I don't think a little extra empty space at the top would hurt.
